### ISSUE TITLE
composer.json is preffixed but also empty autoload psr-4 section is added

### ISSUE THREAD

**Issue by TomasVotruba** [humbug/php-scoper#166]
## Original

File `/vendor/latte/latte/composer.json`

```json
	"autoload": {
		"classmap": ["src/"]
	},
```

## Prefixed

```json
    "autoload": {
        "classmap": [
            "src\/"
        ],
        "psr-4": []
    },
```

Related to: https://github.com/rectorphp/rector/pull/319

**Comment by theofidry** [comment]
That causes an issue? I wouldn't have suspected that :o

**Comment by TomasVotruba** [comment]
It's not cause, just bug that might be related.

**Comment by TomasVotruba** [comment]
I found that 

```bas
composer dump  
```

handles only dependencies of root `composer.json`, so it skips `/vendor` :)

**Comment by theofidry** [comment]
yeah. I added the vendor `composer.json` files but that unnecessary (I forgot about that). What it actually needs is the `vendor/composer/installed.json` file

**Comment by TomasVotruba** [comment]
That might be the case, but still when I delete `/vendor/autoload` and run `composer dump` in root directory, it still skips `/vendor`

**Comment by theofidry** [comment]
You lost me there: if you do `composer dump` then Composer looks for `getcwd().'/vendor/composer/installed.json` file and dump the autoloader from that no? (not sure about your leading `/` but just in case, the `composer dump` you must do in your case is `composer dump-autoload -d=build/rector` or something like that)

**Comment by TomasVotruba** [comment]
So looks like this `vendor/composer/installed.json` works, thanks :+1:  :clap: 

In the meantime I got completelly new error - maybe you've met it already?

```php
PHP Fatal error:  Uncaught Error: Call to undefined function KevinGH\Box\register_aliases() in /var/www/Rector/vendor/humbug/box/bin/box:28
Stack trace:
#0 {main}
  thrown in /var/www/Rector/vendor/humbug/box/bin/box on line 28
```

**Comment by theofidry** [comment]
Try to update your deps again, that function no longer exists (it has been renamed)

**Comment by TomasVotruba** [comment]
Ha, I needed to delete not only `/vendor-bin`, but also `/vendor/bin/box`. 

Composer doesn't update those bin files. Build works afterwards :+1:

**Comment by TomasVotruba** [comment]
It fails on extra space again.

```php
PHP Fatal error:  Namespace declaration statement has to be the very first statement or after any declare call in the script in phar:///var/www/Rector/rector.phar/bin/rector on line 3
```

Where is the code responsible for adding `namespace ...` to unnamespaced files? I'll try to fix that.

---

Will try removing manually to debug more in the meaintime.

**Comment by TomasVotruba** [comment]
Removing shebang works and I can still run it like `./rector.phar`.

I got now error with autoloading, probably Finder in `scoper.inc.php` that just need bit tuning. Errors I like :+1:  I will continue tomorrow.

There should be option to remove the shebang on phar file build.

**Comment by TomasVotruba** [comment]
Ok, so it's `.yml` related error in this package:

```
PHP Fatal error:  Uncaught PhpScoper5a8b08645a07f\Symfony\Component\DependencyInjection\Exception\RuntimeException: Invalid service "SebastianBergmann\Diff\Output\StrictUnifiedDiffOutputBuilder": class "SebastianBergmann\Diff\Output\StrictUnifiedDiffOutputBuilder" does not exist. in phar:///var/www/Rector/rector.phar/vendor/symfony/dependency-injection/Compiler/AbstractRecursivePass.php:109
```

### `services.yml` remains untouched 

```yaml
# services.yml
services:
    _defaults:
        autowire: true

    Rector\ConsoleDiffer\:
        resource: ..

    SebastianBergmann\Diff\Output\StrictUnifiedDiffOutputBuilder:
        arguments:
            $options:
                'fromFile': 'Original'
                'toFile': 'New'

    SebastianBergmann\Diff\Differ:
        arguments:
            - '@SebastianBergmann\Diff\Output\StrictUnifiedDiffOutputBuilder'
```

### Expected

```yaml
# services.yml
services:
    _defaults:
        autowire: true

    PhpScoperPrefix\Rector\ConsoleDiffer\:
        resource: ..

    PhpScoperPrefix\SebastianBergmann\Diff\Output\StrictUnifiedDiffOutputBuilder:
        arguments:
            $options:
                'fromFile': 'Original'
                'toFile': 'New'

    PhpScoperPrefix\SebastianBergmann\Diff\Differ:
        arguments:
            - '@PhpScoperPrefix\SebastianBergmann\Diff\Output\StrictUnifiedDiffOutputBuilder'
```
